/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using PagarmeSDK;
using PagarmeSDK.Utilities;
using PagarmeSDK.Http.Client;
using PagarmeSDK.Http.Response;
using PagarmeSDK.Exceptions;

namespace PagarmeSDK.Controllers
{
    public partial class BaseController
    {
        private static object syncObject = new object();
        private static HTTPClient clientInstance = null;

        public static HTTPClient ClientInstance
        {
            get
            {
                lock(syncObject)
                {
                    if(null == clientInstance)
                    {
                        clientInstance = new HTTPClient()
;
                    }
                    return clientInstance;
                }
            }
            set
            {
                lock (syncObject)
                {
                    if (value is HTTPClient)
                    {
                        clientInstance = value;
                    }
                }
            }
        }

        internal ArrayDeserialization ArrayDeserializationFormat = ArrayDeserialization.Indexed;
        internal static char ParameterSeparator = '&';

        /// <summary>
        /// Validates the response against HTTP errors defined at the API level
        /// </summary>
        /// <param name="_response">The response recieved</param>
        /// <param name="_context">Context of the request and the recieved response</param>
        internal void ValidateResponse(HttpResponse _response, HttpContext _context)
        {
            if (_response.StatusCode == 400)
                throw new PagarmeInvalidRequestException(_context);

            if (_response.StatusCode == 401)
                throw new PagarmeInvalidApiKeyException(_context);

            if (_response.StatusCode == 404)
                throw new PagarmeResourceNotFoundException(_context);

            if (_response.StatusCode == 412)
                throw new PagarmeBusinessValidationException(_context);

            if (_response.StatusCode == 422)
                throw new PagarmeContractValidationException(_context);

            if (_response.StatusCode == 500)
                throw new PagarmeInternalServerErrorException(_context);

            if ((_response.StatusCode < 200) || (_response.StatusCode > 208)) //[200,208] = HTTP OK
                throw new APIException(@"HTTP Response Not OK", _context);
        }
    }
} 



