/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using PagarmeSDK;
using PagarmeSDK.Utilities;
using PagarmeSDK.Http.Request;
using PagarmeSDK.Http.Response;
using PagarmeSDK.Http.Client;
using PagarmeSDK.Exceptions;

namespace PagarmeSDK.Controllers
{
    public partial class DisputesController: BaseController
    {
        private static object syncObject = new object();
        private static DisputesController instance = null;

        internal static DisputesController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new DisputesController();
                    }
                }
                return instance;
            }
        }

        public Models.PagarmeListResponse GetDisputes(int? page = null, int? size = null, string status = null)
        {
            Task<Models.PagarmeListResponse> t = GetDisputesAsync(page, size, status);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeListResponse> GetDisputesAsync(int? page = null, int? size = null, string status = null, CancellationToken cancellationToken = default)
        {
            HttpStringResponse _response = await ExecuteAsync("GET", "/v1/disputes", null, new Dictionary<string, object>()
            {
                { "page", page },
                { "size", size },
                { "status", status }
            }, null, null, cancellationToken).ConfigureAwait(false);

            return DeserializeList(_response);
        }

        public Models.PagarmeObjectResponse GetDispute(string disputeId)
        {
            Task<Models.PagarmeObjectResponse> t = GetDisputeAsync(disputeId);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeObjectResponse> GetDisputeAsync(string disputeId, CancellationToken cancellationToken = default)
        {
            HttpStringResponse _response = await ExecuteAsync("GET", "/v1/disputes/{dispute_id}", new Dictionary<string, object>()
            {
                { "dispute_id", disputeId }
            }, null, null, null, cancellationToken).ConfigureAwait(false);

            return DeserializeObject(_response);
        }

        public Models.PagarmeObjectResponse CreateDisputeEvidence(string disputeId, Models.CreateDisputeEvidenceRequest request)
        {
            Task<Models.PagarmeObjectResponse> t = CreateDisputeEvidenceAsync(disputeId, request);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeObjectResponse> CreateDisputeEvidenceAsync(string disputeId, Models.CreateDisputeEvidenceRequest request, CancellationToken cancellationToken = default)
        {
            StringBuilder _queryBuilder = new StringBuilder(Configuration.BaseUri);
            _queryBuilder.Append("/v1/disputes/{dispute_id}/evidences");
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "dispute_id", disputeId }
            });

            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", Configuration.UserAgent },
                { "accept", "application/json" }
            };

            var _form = new List<KeyValuePair<string, object>>();
            if (request?.Files != null)
            {
                foreach (FileStreamInfo file in request.Files)
                {
                    _form.Add(new KeyValuePair<string, object>("files", file));
                }
            }

            HttpRequest _request = HTTPClient.Post(_queryUrl, _headers, _form, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request, cancellationToken).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request, _response);
            base.ValidateResponse(_response, _context);
            return DeserializeObject(_response);
        }

        private async Task<HttpStringResponse> ExecuteAsync(string method, string path, Dictionary<string, object> templateParameters, Dictionary<string, object> queryParameters, object body, string idempotencyKey, CancellationToken cancellationToken)
        {
            StringBuilder _queryBuilder = new StringBuilder(Configuration.BaseUri);
            _queryBuilder.Append(path);
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, templateParameters);
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, queryParameters, ArrayDeserializationFormat, ParameterSeparator);

            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", Configuration.UserAgent },
                { "accept", "application/json" }
            };

            if (body != null)
            {
                _headers.Add("content-type", "application/json; charset=utf-8");
            }

            if (idempotencyKey != null)
            {
                _headers.Add("idempotency-key", idempotencyKey);
            }

            string _body = body == null ? null : APIHelper.JsonSerialize(body);
            HttpRequest _request = method == "POST"
                ? HTTPClient.PostBody(_queryUrl, _headers, _body, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword)
                : HTTPClient.Get(_queryUrl, _headers, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request, cancellationToken).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request, _response);
            base.ValidateResponse(_response, _context);
            return _response;
        }

        private Models.PagarmeObjectResponse DeserializeObject(HttpStringResponse response)
        {
            HttpContext _context = new HttpContext(null, response);
            try
            {
                return APIHelper.JsonDeserialize<Models.PagarmeObjectResponse>(response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        private Models.PagarmeListResponse DeserializeList(HttpStringResponse response)
        {
            HttpContext _context = new HttpContext(null, response);
            try
            {
                return APIHelper.JsonDeserialize<Models.PagarmeListResponse>(response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }
    }
}

