/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using PagarmeSDK;
using PagarmeSDK.Utilities;
using PagarmeSDK.Http.Request;
using PagarmeSDK.Http.Response;
using PagarmeSDK.Http.Client;
using PagarmeSDK.Exceptions;

namespace PagarmeSDK.Controllers
{
    public partial class PaymentLinksController: BaseController
    {
        private static object syncObject = new object();
        private static PaymentLinksController instance = null;

        internal static PaymentLinksController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new PaymentLinksController();
                    }
                }
                return instance;
            }
        }

        public Models.PagarmeObjectResponse CreatePaymentLink(Models.CreatePaymentLinkRequest request, string idempotencyKey = null)
        {
            Task<Models.PagarmeObjectResponse> t = CreatePaymentLinkAsync(request, idempotencyKey);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeObjectResponse> CreatePaymentLinkAsync(Models.CreatePaymentLinkRequest request, string idempotencyKey = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteObjectAsync("POST", "/paymentlinks", null, request, idempotencyKey, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeListResponse GetPaymentLinks(int? page = null, int? size = null, string status = null)
        {
            Task<Models.PagarmeListResponse> t = GetPaymentLinksAsync(page, size, status);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeListResponse> GetPaymentLinksAsync(int? page = null, int? size = null, string status = null, CancellationToken cancellationToken = default)
        {
            var queryParameters = new Dictionary<string, object>()
            {
                { "page", page },
                { "size", size },
                { "status", status }
            };

            return await ExecuteListAsync("GET", "/paymentlinks", queryParameters, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeObjectResponse GetPaymentLink(string paymentLinkId)
        {
            Task<Models.PagarmeObjectResponse> t = GetPaymentLinkAsync(paymentLinkId);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeObjectResponse> GetPaymentLinkAsync(string paymentLinkId, CancellationToken cancellationToken = default)
        {
            return await ExecuteObjectAsync("GET", "/paymentlinks/{payment_link_id}", new Dictionary<string, object>()
            {
                { "payment_link_id", paymentLinkId }
            }, null, null, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeObjectResponse ActivatePaymentLink(string paymentLinkId, string idempotencyKey = null)
        {
            Task<Models.PagarmeObjectResponse> t = ActivatePaymentLinkAsync(paymentLinkId, idempotencyKey);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeObjectResponse> ActivatePaymentLinkAsync(string paymentLinkId, string idempotencyKey = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteObjectAsync("PATCH", "/paymentlinks/{payment_link_id}/activate", new Dictionary<string, object>()
            {
                { "payment_link_id", paymentLinkId }
            }, null, idempotencyKey, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeObjectResponse CancelPaymentLink(string paymentLinkId, string idempotencyKey = null)
        {
            Task<Models.PagarmeObjectResponse> t = CancelPaymentLinkAsync(paymentLinkId, idempotencyKey);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeObjectResponse> CancelPaymentLinkAsync(string paymentLinkId, string idempotencyKey = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteObjectAsync("PATCH", "/paymentlinks/{payment_link_id}/cancel", new Dictionary<string, object>()
            {
                { "payment_link_id", paymentLinkId }
            }, null, idempotencyKey, cancellationToken).ConfigureAwait(false);
        }

        private async Task<Models.PagarmeObjectResponse> ExecuteObjectAsync(string method, string path, Dictionary<string, object> templateParameters, object body, string idempotencyKey, CancellationToken cancellationToken)
        {
            HttpStringResponse _response = await ExecuteAsync(method, path, templateParameters, null, body, idempotencyKey, cancellationToken).ConfigureAwait(false);
            HttpContext _context = new HttpContext(null, _response);
            try
            {
                return APIHelper.JsonDeserialize<Models.PagarmeObjectResponse>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        private async Task<Models.PagarmeListResponse> ExecuteListAsync(string method, string path, Dictionary<string, object> queryParameters, CancellationToken cancellationToken)
        {
            HttpStringResponse _response = await ExecuteAsync(method, path, null, queryParameters, null, null, cancellationToken).ConfigureAwait(false);
            HttpContext _context = new HttpContext(null, _response);
            try
            {
                return APIHelper.JsonDeserialize<Models.PagarmeListResponse>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        private async Task<HttpStringResponse> ExecuteAsync(string method, string path, Dictionary<string, object> templateParameters, Dictionary<string, object> queryParameters, object body, string idempotencyKey, CancellationToken cancellationToken)
        {
            string _baseUri = Configuration.BaseUri;
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append(path);

            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, templateParameters);
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, queryParameters, ArrayDeserializationFormat, ParameterSeparator);

            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", Configuration.UserAgent },
                { "accept", "application/json" }
            };

            if (body != null || method == "POST" || method == "PATCH")
            {
                _headers.Add("content-type", "application/json; charset=utf-8");
            }

            if (idempotencyKey != null)
            {
                _headers.Add("idempotency-key", idempotencyKey);
            }

            string _body = body == null ? null : APIHelper.JsonSerialize(body);
            HttpRequest _request;
            switch (method)
            {
                case "GET":
                    _request = HTTPClient.Get(_queryUrl, _headers, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);
                    break;
                case "POST":
                    _request = HTTPClient.PostBody(_queryUrl, _headers, _body, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);
                    break;
                case "PATCH":
                    _request = HTTPClient.PatchBody(_queryUrl, _headers, _body, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);
                    break;
                default:
                    throw new ArgumentException("Unsupported HTTP method.", nameof(method));
            }

            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request, cancellationToken).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request, _response);
            base.ValidateResponse(_response, _context);
            return _response;
        }
    }
}

