/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using PagarmeSDK;
using PagarmeSDK.Utilities;
using PagarmeSDK.Http.Request;
using PagarmeSDK.Http.Response;
using PagarmeSDK.Http.Client;
using PagarmeSDK.Exceptions;

namespace PagarmeSDK.Controllers
{
    public partial class ReceivablesController: BaseController
    {
        private static object syncObject = new object();
        private static ReceivablesController instance = null;

        internal static ReceivablesController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new ReceivablesController();
                    }
                }
                return instance;
            }
        }

        public Models.PagarmeListResponse GetPayables(int? page = null, int? size = null, string recipientId = null)
        {
            Task<Models.PagarmeListResponse> t = GetPayablesAsync(page, size, recipientId);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeListResponse> GetPayablesAsync(int? page = null, int? size = null, string recipientId = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteListAsync("GET", "/payables", null, new Dictionary<string, object>()
            {
                { "page", page },
                { "size", size },
                { "recipient_id", recipientId }
            }, null, null, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeListResponse GetSettlements(int? page = null, int? size = null, string recipientId = null)
        {
            Task<Models.PagarmeListResponse> t = GetSettlementsAsync(page, size, recipientId);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeListResponse> GetSettlementsAsync(int? page = null, int? size = null, string recipientId = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteListAsync("GET", "/settlements", null, new Dictionary<string, object>()
            {
                { "page", page },
                { "size", size },
                { "recipient_id", recipientId }
            }, null, null, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeObjectResponse GetSettlement(string settlementId)
        {
            Task<Models.PagarmeObjectResponse> t = GetSettlementAsync(settlementId);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeObjectResponse> GetSettlementAsync(string settlementId, CancellationToken cancellationToken = default)
        {
            return await ExecuteObjectAsync("GET", "/settlements/{settlement_id}", new Dictionary<string, object>()
            {
                { "settlement_id", settlementId }
            }, null, null, null, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeListResponse GetRecipientSettlements(string recipientId, int? page = null, int? size = null)
        {
            Task<Models.PagarmeListResponse> t = GetRecipientSettlementsAsync(recipientId, page, size);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeListResponse> GetRecipientSettlementsAsync(string recipientId, int? page = null, int? size = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteListAsync("GET", "/recipients/{recipient_id}/settlements", new Dictionary<string, object>()
            {
                { "recipient_id", recipientId }
            }, new Dictionary<string, object>()
            {
                { "page", page },
                { "size", size }
            }, null, null, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeListResponse GetRecipientReceivableUnits(string recipientId, int? page = null, int? size = null)
        {
            Task<Models.PagarmeListResponse> t = GetRecipientReceivableUnitsAsync(recipientId, page, size);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeListResponse> GetRecipientReceivableUnitsAsync(string recipientId, int? page = null, int? size = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteListAsync("GET", "/recipients/{recipient_id}/receivable-units", new Dictionary<string, object>()
            {
                { "recipient_id", recipientId }
            }, new Dictionary<string, object>()
            {
                { "page", page },
                { "size", size }
            }, null, null, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeListResponse GetSettlementObligations(int? page = null, int? size = null)
        {
            Task<Models.PagarmeListResponse> t = GetSettlementObligationsAsync(page, size);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeListResponse> GetSettlementObligationsAsync(int? page = null, int? size = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteListAsync("GET", "/settlement-obligations", null, new Dictionary<string, object>()
            {
                { "page", page },
                { "size", size }
            }, null, null, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeListResponse GetSettlementObligationContracts(int? page = null, int? size = null)
        {
            Task<Models.PagarmeListResponse> t = GetSettlementObligationContractsAsync(page, size);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeListResponse> GetSettlementObligationContractsAsync(int? page = null, int? size = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteListAsync("GET", "/settlement_obligations/contracts", null, new Dictionary<string, object>()
            {
                { "page", page },
                { "size", size }
            }, null, null, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeListResponse GetContestations(int? page = null, int? size = null)
        {
            Task<Models.PagarmeListResponse> t = GetContestationsAsync(page, size);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeListResponse> GetContestationsAsync(int? page = null, int? size = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteListAsync("GET", "/contestations", null, new Dictionary<string, object>()
            {
                { "page", page },
                { "size", size }
            }, null, null, cancellationToken).ConfigureAwait(false);
        }

        public Models.PagarmeObjectResponse CreateContestation(Models.CreateContestationRequest request, string idempotencyKey = null)
        {
            Task<Models.PagarmeObjectResponse> t = CreateContestationAsync(request, idempotencyKey);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        public async Task<Models.PagarmeObjectResponse> CreateContestationAsync(Models.CreateContestationRequest request, string idempotencyKey = null, CancellationToken cancellationToken = default)
        {
            return await ExecuteObjectAsync("POST", "/contestations", null, null, request, idempotencyKey, cancellationToken).ConfigureAwait(false);
        }

        private async Task<Models.PagarmeObjectResponse> ExecuteObjectAsync(string method, string path, Dictionary<string, object> templateParameters, Dictionary<string, object> queryParameters, object body, string idempotencyKey, CancellationToken cancellationToken)
        {
            HttpStringResponse _response = await ExecuteAsync(method, path, templateParameters, queryParameters, body, idempotencyKey, cancellationToken).ConfigureAwait(false);
            HttpContext _context = new HttpContext(null, _response);
            try
            {
                return APIHelper.JsonDeserialize<Models.PagarmeObjectResponse>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        private async Task<Models.PagarmeListResponse> ExecuteListAsync(string method, string path, Dictionary<string, object> templateParameters, Dictionary<string, object> queryParameters, object body, string idempotencyKey, CancellationToken cancellationToken)
        {
            HttpStringResponse _response = await ExecuteAsync(method, path, templateParameters, queryParameters, body, idempotencyKey, cancellationToken).ConfigureAwait(false);
            HttpContext _context = new HttpContext(null, _response);
            try
            {
                return APIHelper.JsonDeserialize<Models.PagarmeListResponse>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        private async Task<HttpStringResponse> ExecuteAsync(string method, string path, Dictionary<string, object> templateParameters, Dictionary<string, object> queryParameters, object body, string idempotencyKey, CancellationToken cancellationToken)
        {
            StringBuilder _queryBuilder = new StringBuilder(Configuration.BaseUri);
            _queryBuilder.Append(path);
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, templateParameters);
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, queryParameters, ArrayDeserializationFormat, ParameterSeparator);

            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", Configuration.UserAgent },
                { "accept", "application/json" }
            };

            if (body != null || method == "POST")
            {
                _headers.Add("content-type", "application/json; charset=utf-8");
            }

            if (idempotencyKey != null)
            {
                _headers.Add("idempotency-key", idempotencyKey);
            }

            string _body = body == null ? null : APIHelper.JsonSerialize(body);
            HttpRequest _request = method == "POST"
                ? HTTPClient.PostBody(_queryUrl, _headers, _body, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword)
                : HTTPClient.Get(_queryUrl, _headers, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request, cancellationToken).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request, _response);
            base.ValidateResponse(_response, _context);
            return _response;
        }
    }
}

