/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PagarmeSDK;
using PagarmeSDK.Utilities;


namespace PagarmeSDK.Models
{
    public class CreateTransferSettingsRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool transferEnabled;
        private string transferInterval;
        private int transferDay;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("transfer_enabled")]
        public bool TransferEnabled 
        { 
            get 
            {
                return this.transferEnabled; 
            } 
            set 
            {
                this.transferEnabled = value;
                onPropertyChanged("TransferEnabled");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("transfer_interval")]
        public string TransferInterval 
        { 
            get 
            {
                return this.transferInterval; 
            } 
            set 
            {
                this.transferInterval = value;
                onPropertyChanged("TransferInterval");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("transfer_day")]
        public int TransferDay 
        { 
            get 
            {
                return this.transferDay; 
            } 
            set 
            {
                this.transferDay = value;
                onPropertyChanged("TransferDay");
            }
        }

        /// <summary>
        /// Validates transfer settings.
        /// </summary>
        public override void Validate()
        {
            ValidateAllowedValues("TransferInterval", this.transferInterval, "daily", "weekly", "monthly");
            ValidateTransferDay(this.transferInterval, this.transferDay);
        }

        internal static void ValidateTransferDay(string transferInterval, int transferDay)
        {
            if (string.IsNullOrWhiteSpace(transferInterval))
            {
                return;
            }

            string normalizedTransferInterval = transferInterval.ToLower(CultureInfo.InvariantCulture);

            if (normalizedTransferInterval == "daily" && transferDay != 0)
            {
                throw new ArgumentException("TransferDay must be 0 when TransferInterval is daily.", "TransferDay");
            }

            if (normalizedTransferInterval == "weekly" && (transferDay < 1 || transferDay > 5))
            {
                throw new ArgumentException("TransferDay must be between 1 and 5 when TransferInterval is weekly.", "TransferDay");
            }

            if (normalizedTransferInterval == "monthly" && (transferDay < 1 || transferDay > 31))
            {
                throw new ArgumentException("TransferDay must be between 1 and 31 when TransferInterval is monthly.", "TransferDay");
            }
        }
    }
} 
