/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PagarmeSDK;
using PagarmeSDK.Utilities;


namespace PagarmeSDK.Models
{
    public class CreateRecipientRegisterInformationRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name;
        private string companyName;
        private string tradingName;
        private string email;
        private string document;
        private string type;
        private string siteUrl;
        private string motherName;
        private string birthdate;
        private long? monthlyIncome;
        private string professionalOccupation;
        private long? annualRevenue;
        private string corporationType;
        private string foundingDate;
        private string cnae;
        private bool? selfDeclaredRepresentative;
        private bool? selfDeclaredLegalRepresentative;
        private Models.CreateRecipientRegisterInformationAddressRequest address;
        private Models.CreateRecipientRegisterInformationAddressRequest mainAddress;
        private List<Models.CreateRecipientRegisterInformationPhoneRequest> phoneNumbers;
        private List<Models.CreateRecipientRegisterInformationRequest> managingPartners;

        /// <summary>
        /// Recipient name
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Recipient company name
        /// </summary>
        [JsonProperty("company_name")]
        public string CompanyName 
        { 
            get 
            {
                return this.companyName; 
            } 
            set 
            {
                this.companyName = value;
                onPropertyChanged("CompanyName");
            }
        }

        /// <summary>
        /// Recipient trading name
        /// </summary>
        [JsonProperty("trading_name")]
        public string TradingName 
        { 
            get 
            {
                return this.tradingName; 
            } 
            set 
            {
                this.tradingName = value;
                onPropertyChanged("TradingName");
            }
        }

        /// <summary>
        /// Recipient email
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// Recipient document number
        /// </summary>
        [JsonProperty("document")]
        public string Document 
        { 
            get 
            {
                return this.document; 
            } 
            set 
            {
                this.document = value;
                onPropertyChanged("Document");
            }
        }

        /// <summary>
        /// Recipient type
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// Recipient website
        /// </summary>
        [JsonProperty("site_url")]
        public string SiteUrl 
        { 
            get 
            {
                return this.siteUrl; 
            } 
            set 
            {
                this.siteUrl = value;
                onPropertyChanged("SiteUrl");
            }
        }

        /// <summary>
        /// Recipient mother name
        /// </summary>
        [JsonProperty("mother_name")]
        public string MotherName 
        { 
            get 
            {
                return this.motherName; 
            } 
            set 
            {
                this.motherName = value;
                onPropertyChanged("MotherName");
            }
        }

        /// <summary>
        /// Recipient birthdate
        /// </summary>
        [JsonProperty("birthdate")]
        public string Birthdate 
        { 
            get 
            {
                return this.birthdate; 
            } 
            set 
            {
                this.birthdate = value;
                onPropertyChanged("Birthdate");
            }
        }

        /// <summary>
        /// Recipient monthly income
        /// </summary>
        [JsonProperty("monthly_income")]
        public long? MonthlyIncome 
        { 
            get 
            {
                return this.monthlyIncome; 
            } 
            set 
            {
                this.monthlyIncome = value;
                onPropertyChanged("MonthlyIncome");
            }
        }

        /// <summary>
        /// Recipient professional occupation
        /// </summary>
        [JsonProperty("professional_occupation")]
        public string ProfessionalOccupation 
        { 
            get 
            {
                return this.professionalOccupation; 
            } 
            set 
            {
                this.professionalOccupation = value;
                onPropertyChanged("ProfessionalOccupation");
            }
        }

        /// <summary>
        /// Recipient annual revenue
        /// </summary>
        [JsonProperty("annual_revenue")]
        public long? AnnualRevenue 
        { 
            get 
            {
                return this.annualRevenue; 
            } 
            set 
            {
                this.annualRevenue = value;
                onPropertyChanged("AnnualRevenue");
            }
        }

        /// <summary>
        /// Recipient corporation type
        /// </summary>
        [JsonProperty("corporation_type")]
        public string CorporationType 
        { 
            get 
            {
                return this.corporationType; 
            } 
            set 
            {
                this.corporationType = value;
                onPropertyChanged("CorporationType");
            }
        }

        /// <summary>
        /// Recipient founding date
        /// </summary>
        [JsonProperty("founding_date")]
        public string FoundingDate 
        { 
            get 
            {
                return this.foundingDate; 
            } 
            set 
            {
                this.foundingDate = value;
                onPropertyChanged("FoundingDate");
            }
        }

        /// <summary>
        /// Recipient CNAE
        /// </summary>
        [JsonProperty("cnae")]
        public string Cnae 
        { 
            get 
            {
                return this.cnae; 
            } 
            set 
            {
                this.cnae = value;
                onPropertyChanged("Cnae");
            }
        }

        /// <summary>
        /// Legal representative self declaration
        /// </summary>
        [JsonProperty("self_declared_representative")]
        public bool? SelfDeclaredRepresentative 
        { 
            get 
            {
                return this.selfDeclaredRepresentative; 
            } 
            set 
            {
                this.selfDeclaredRepresentative = value;
                onPropertyChanged("SelfDeclaredRepresentative");
            }
        }

        /// <summary>
        /// Legal representative self declaration
        /// </summary>
        [JsonProperty("self_declared_legal_representative")]
        public bool? SelfDeclaredLegalRepresentative 
        { 
            get 
            {
                return this.selfDeclaredLegalRepresentative; 
            } 
            set 
            {
                this.selfDeclaredLegalRepresentative = value;
                onPropertyChanged("SelfDeclaredLegalRepresentative");
            }
        }

        /// <summary>
        /// Recipient address
        /// </summary>
        [JsonProperty("address")]
        public Models.CreateRecipientRegisterInformationAddressRequest Address 
        { 
            get 
            {
                return this.address; 
            } 
            set 
            {
                this.address = value;
                onPropertyChanged("Address");
            }
        }

        /// <summary>
        /// Recipient main address
        /// </summary>
        [JsonProperty("main_address")]
        public Models.CreateRecipientRegisterInformationAddressRequest MainAddress 
        { 
            get 
            {
                return this.mainAddress; 
            } 
            set 
            {
                this.mainAddress = value;
                onPropertyChanged("MainAddress");
            }
        }

        /// <summary>
        /// Recipient phone numbers
        /// </summary>
        [JsonProperty("phone_numbers")]
        public List<Models.CreateRecipientRegisterInformationPhoneRequest> PhoneNumbers 
        { 
            get 
            {
                return this.phoneNumbers; 
            } 
            set 
            {
                this.phoneNumbers = value;
                onPropertyChanged("PhoneNumbers");
            }
        }

        /// <summary>
        /// Recipient managing partners
        /// </summary>
        [JsonProperty("managing_partners")]
        public List<Models.CreateRecipientRegisterInformationRequest> ManagingPartners 
        { 
            get 
            {
                return this.managingPartners; 
            } 
            set 
            {
                this.managingPartners = value;
                onPropertyChanged("ManagingPartners");
            }
        }
    }
} 
