/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PagarmeSDK;
using PagarmeSDK.Utilities;


namespace PagarmeSDK.Models
{
    public class CreateRecipientRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string description;
        private Models.CreateRecipientRegisterInformationRequest registerInformation;
        private Models.CreateBankAccountRequest defaultBankAccount;
        private Dictionary<string, string> metadata;
        private Models.CreateTransferSettingsRequest transferSettings;
        private Models.CreateAutomaticAnticipationSettingsRequest automaticAnticipationSettings;
        private string code;
        private string paymentMode = "bank_transfer";

        /// <summary>
        /// Recipient name
        /// </summary>
        [JsonIgnore]
        public string Name 
        { 
            get 
            {
                return this.registerInformation?.Name; 
            } 
            set 
            {
                GetOrCreateRegisterInformation().Name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Recipient email
        /// </summary>
        [JsonIgnore]
        public string Email 
        { 
            get 
            {
                return this.registerInformation?.Email; 
            } 
            set 
            {
                GetOrCreateRegisterInformation().Email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// Recipient description
        /// </summary>
        [JsonIgnore]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Recipient document number
        /// </summary>
        [JsonIgnore]
        public string Document 
        { 
            get 
            {
                return this.registerInformation?.Document; 
            } 
            set 
            {
                GetOrCreateRegisterInformation().Document = value;
                onPropertyChanged("Document");
            }
        }

        /// <summary>
        /// Recipient type
        /// </summary>
        [JsonIgnore]
        public string Type 
        { 
            get 
            {
                return this.registerInformation?.Type; 
            } 
            set 
            {
                GetOrCreateRegisterInformation().Type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// Recipient registration information
        /// </summary>
        [JsonProperty("register_information")]
        public Models.CreateRecipientRegisterInformationRequest RegisterInformation 
        { 
            get 
            {
                return this.registerInformation; 
            } 
            set 
            {
                this.registerInformation = value;
                onPropertyChanged("RegisterInformation");
            }
        }

        /// <summary>
        /// Bank account
        /// </summary>
        [JsonProperty("default_bank_account")]
        public Models.CreateBankAccountRequest DefaultBankAccount 
        { 
            get 
            {
                return this.defaultBankAccount; 
            } 
            set 
            {
                this.defaultBankAccount = value;
                onPropertyChanged("DefaultBankAccount");
            }
        }

        /// <summary>
        /// Metadata
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata 
        { 
            get 
            {
                return this.metadata; 
            } 
            set 
            {
                this.metadata = value;
                onPropertyChanged("Metadata");
            }
        }

        /// <summary>
        /// Receiver Transfer Information
        /// </summary>
        [JsonProperty("transfer_settings")]
        public Models.CreateTransferSettingsRequest TransferSettings 
        { 
            get 
            {
                return this.transferSettings; 
            } 
            set 
            {
                this.transferSettings = value;
                onPropertyChanged("TransferSettings");
            }
        }

        /// <summary>
        /// Receiver automatic anticipation information
        /// </summary>
        [JsonProperty("automatic_anticipation_settings")]
        public Models.CreateAutomaticAnticipationSettingsRequest AutomaticAnticipationSettings 
        { 
            get 
            {
                return this.automaticAnticipationSettings; 
            } 
            set 
            {
                this.automaticAnticipationSettings = value;
                onPropertyChanged("AutomaticAnticipationSettings");
            }
        }

        /// <summary>
        /// Recipient code
        /// </summary>
        [JsonProperty("code")]
        public string Code 
        { 
            get 
            {
                return this.code; 
            } 
            set 
            {
                this.code = value;
                onPropertyChanged("Code");
            }
        }

        /// <summary>
        /// Payment mode
        /// </summary>
        [JsonIgnore]
        public string PaymentMode 
        { 
            get 
            {
                return this.paymentMode; 
            } 
            set 
            {
                this.paymentMode = value;
                onPropertyChanged("PaymentMode");
            }
        }

        private Models.CreateRecipientRegisterInformationRequest GetOrCreateRegisterInformation()
        {
            if (this.registerInformation == null)
            {
                this.registerInformation = new Models.CreateRecipientRegisterInformationRequest();
            }

            return this.registerInformation;
        }

        /// <summary>
        /// Validates recipient creation data.
        /// </summary>
        public override void Validate()
        {
            this.registerInformation?.Validate();
            this.defaultBankAccount?.Validate();
            this.transferSettings?.Validate();
            this.automaticAnticipationSettings?.Validate();
        }
    }
} 
