/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PagarmeSDK;
using PagarmeSDK.Utilities;


namespace PagarmeSDK.Models
{
    public class CreateRecipientRegisterInformationAddressRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string street;
        private string complementary;
        private string streetNumber;
        private string neighborhood;
        private string city;
        private string state;
        private string zipCode;
        private string referencePoint;

        /// <summary>
        /// Street
        /// </summary>
        [JsonProperty("street")]
        public string Street 
        { 
            get 
            {
                return this.street; 
            } 
            set 
            {
                this.street = value;
                onPropertyChanged("Street");
            }
        }

        /// <summary>
        /// Complement
        /// </summary>
        [JsonProperty("complementary")]
        public string Complementary 
        { 
            get 
            {
                return this.complementary; 
            } 
            set 
            {
                this.complementary = value;
                onPropertyChanged("Complementary");
            }
        }

        /// <summary>
        /// Street number
        /// </summary>
        [JsonProperty("street_number")]
        public string StreetNumber 
        { 
            get 
            {
                return this.streetNumber; 
            } 
            set 
            {
                this.streetNumber = value;
                onPropertyChanged("StreetNumber");
            }
        }

        /// <summary>
        /// Neighborhood
        /// </summary>
        [JsonProperty("neighborhood")]
        public string Neighborhood 
        { 
            get 
            {
                return this.neighborhood; 
            } 
            set 
            {
                this.neighborhood = value;
                onPropertyChanged("Neighborhood");
            }
        }

        /// <summary>
        /// City
        /// </summary>
        [JsonProperty("city")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// State
        /// </summary>
        [JsonProperty("state")]
        public string State 
        { 
            get 
            {
                return this.state; 
            } 
            set 
            {
                this.state = value;
                onPropertyChanged("State");
            }
        }

        /// <summary>
        /// Zip code
        /// </summary>
        [JsonProperty("zip_code")]
        public string ZipCode 
        { 
            get 
            {
                return this.zipCode; 
            } 
            set 
            {
                this.zipCode = value;
                onPropertyChanged("ZipCode");
            }
        }

        /// <summary>
        /// Reference point
        /// </summary>
        [JsonProperty("reference_point")]
        public string ReferencePoint 
        { 
            get 
            {
                return this.referencePoint; 
            } 
            set 
            {
                this.referencePoint = value;
                onPropertyChanged("ReferencePoint");
            }
        }
    }
} 

