/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PagarmeSDK;
using PagarmeSDK.Utilities;


namespace PagarmeSDK.Models
{
    public class CreateAutomaticAnticipationSettingsRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool enabled;
        private string type;
        private string volumePercentage;
        private string delay;
        private List<string> days;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("enabled")]
        public bool Enabled 
        { 
            get 
            {
                return this.enabled; 
            } 
            set 
            {
                this.enabled = value;
                onPropertyChanged("Enabled");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("volume_percentage")]
        public string VolumePercentage 
        { 
            get 
            {
                return this.volumePercentage; 
            } 
            set 
            {
                this.volumePercentage = value;
                onPropertyChanged("VolumePercentage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("delay")]
        public string Delay 
        { 
            get 
            {
                return this.delay; 
            } 
            set 
            {
                this.delay = value;
                onPropertyChanged("Delay");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("days")]
        public List<string> Days 
        { 
            get 
            {
                return this.days; 
            } 
            set 
            {
                this.days = value;
                onPropertyChanged("Days");
            }
        }

        /// <summary>
        /// Validates automatic anticipation settings.
        /// </summary>
        public override void Validate()
        {
            ValidateAllowedValues("Type", this.type, "full", "1025");
            ValidateAutomaticAnticipationValues(this.volumePercentage, this.delay, this.days);
        }

        internal static void ValidateAutomaticAnticipationValues(string volumePercentage, string delay, List<string> days)
        {
            ValidateIntegerRange("VolumePercentage", volumePercentage, 0, 100);
            ValidateIntegerMin("Delay", delay, 0);

            if (days == null)
            {
                return;
            }

            foreach (string day in days)
            {
                ValidateIntegerRange("Days", day, 1, 31);
            }
        }

        private static void ValidateIntegerRange(string propertyName, string value, int minValue, int maxValue)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return;
            }

            if (!int.TryParse(value, out int parsedValue) || parsedValue < minValue || parsedValue > maxValue)
            {
                throw new ArgumentException(string.Format("{0} must be an integer between {1} and {2}. Received: {3}", propertyName, minValue, maxValue, value), propertyName);
            }
        }

        private static void ValidateIntegerMin(string propertyName, string value, int minValue)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return;
            }

            if (!int.TryParse(value, out int parsedValue) || parsedValue < minValue)
            {
                throw new ArgumentException(string.Format("{0} must be an integer greater than or equal to {1}. Received: {2}", propertyName, minValue, value), propertyName);
            }
        }
    }
} 
