/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System.Collections.Generic;
using PagarmeSDK.Http.Client;

namespace PagarmeSDK.Models
{
    public class CreateDisputeEvidenceRequest : BaseModel
    {
        private List<FileStreamInfo> files;

        /// <summary>
        /// Evidence PDF files.
        /// </summary>
        public List<FileStreamInfo> Files
        {
            get
            {
                return this.files;
            }
            set
            {
                this.files = value;
                onPropertyChanged("Files");
            }
        }
    }
}

