/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace PagarmeSDK.Models
{
    public class GetRecipientKycLinkResponse : BaseModel
    {
        private string url;
        private string base64Qrcode;
        private DateTime expiresAt;

        /// <summary>
        /// KYC link URL.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }
            set
            {
                this.url = value;
                onPropertyChanged("Url");
            }
        }

        /// <summary>
        /// Base64 QR Code.
        /// </summary>
        [JsonProperty("base64_qrcode")]
        public string Base64Qrcode
        {
            get
            {
                return this.base64Qrcode;
            }
            set
            {
                this.base64Qrcode = value;
                onPropertyChanged("Base64Qrcode");
            }
        }

        /// <summary>
        /// Expiration date.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("expires_at")]
        public DateTime ExpiresAt
        {
            get
            {
                return this.expiresAt;
            }
            set
            {
                this.expiresAt = value;
                onPropertyChanged("ExpiresAt");
            }
        }
    }
}

