/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace PagarmeSDK.Models
{
    public class PagarmeListResponse : BaseModel
    {
        private List<JObject> data;
        private Models.PagingResponse paging;
        private Dictionary<string, JToken> additionalProperties;

        /// <summary>
        /// Response data.
        /// </summary>
        [JsonProperty("data")]
        public List<JObject> Data
        {
            get
            {
                return this.data;
            }
            set
            {
                this.data = value;
                onPropertyChanged("Data");
            }
        }

        /// <summary>
        /// Paging information.
        /// </summary>
        [JsonProperty("paging")]
        public Models.PagingResponse Paging
        {
            get
            {
                return this.paging;
            }
            set
            {
                this.paging = value;
                onPropertyChanged("Paging");
            }
        }

        /// <summary>
        /// Additional properties returned by the API.
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JToken> AdditionalProperties
        {
            get
            {
                return this.additionalProperties;
            }
            set
            {
                this.additionalProperties = value;
                onPropertyChanged("AdditionalProperties");
            }
        }
    }
}

