/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace PagarmeSDK.Models
{
    public class PagarmeObjectResponse : BaseModel
    {
        private Dictionary<string, JToken> additionalProperties;

        /// <summary>
        /// Additional properties returned by the API.
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JToken> AdditionalProperties
        {
            get
            {
                return this.additionalProperties;
            }
            set
            {
                this.additionalProperties = value;
                onPropertyChanged("AdditionalProperties");
            }
        }
    }
}

