/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PagarmeSDK;
using PagarmeSDK.Utilities;


namespace PagarmeSDK.Models
{
    public class UpdateAutomaticAnticipationSettingsRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool? enabled;
        private string type;
        private string volumePercentage;
        private string delay;
        private List<string> days;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("enabled")]
        public bool? Enabled 
        { 
            get 
            {
                return this.enabled; 
            } 
            set 
            {
                this.enabled = value;
                onPropertyChanged("Enabled");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("volume_percentage")]
        public string VolumePercentage 
        { 
            get 
            {
                return this.volumePercentage; 
            } 
            set 
            {
                this.volumePercentage = value;
                onPropertyChanged("VolumePercentage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("delay")]
        public string Delay 
        { 
            get 
            {
                return this.delay; 
            } 
            set 
            {
                this.delay = value;
                onPropertyChanged("Delay");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("days")]
        public List<string> Days 
        { 
            get 
            {
                return this.days; 
            } 
            set 
            {
                this.days = value;
                onPropertyChanged("Days");
            }
        }

        /// <summary>
        /// Validates automatic anticipation settings.
        /// </summary>
        public override void Validate()
        {
            ValidateAllowedValues("Type", this.type, "full", "1025");
            CreateAutomaticAnticipationSettingsRequest.ValidateAutomaticAnticipationValues(this.volumePercentage, this.delay, this.days);
        }
    }
} 
