/*
 * PagarmeSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PagarmeSDK;
using PagarmeSDK.Utilities;


namespace PagarmeSDK.Models
{
    public class UpdateRecipientRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string description;
        private string status;
        private Models.CreateRecipientRegisterInformationRequest registerInformation;
        private Dictionary<string, string> metadata;

        /// <summary>
        /// Name
        /// </summary>
        [JsonIgnore]
        public string Name 
        { 
            get 
            {
                return this.registerInformation?.Name; 
            } 
            set 
            {
                GetOrCreateRegisterInformation().Name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Email
        /// </summary>
        [JsonIgnore]
        public string Email 
        { 
            get 
            {
                return this.registerInformation?.Email; 
            } 
            set 
            {
                GetOrCreateRegisterInformation().Email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// Description
        /// </summary>
        [JsonIgnore]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Document
        /// </summary>
        [JsonIgnore]
        public string Document 
        { 
            get 
            {
                return this.registerInformation?.Document; 
            } 
            set 
            {
                GetOrCreateRegisterInformation().Document = value;
                onPropertyChanged("Document");
            }
        }

        /// <summary>
        /// Type
        /// </summary>
        [JsonIgnore]
        public string Type 
        { 
            get 
            {
                return this.registerInformation?.Type; 
            } 
            set 
            {
                GetOrCreateRegisterInformation().Type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// Status
        /// </summary>
        [JsonIgnore]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Recipient registration information
        /// </summary>
        [JsonProperty("register_information")]
        public Models.CreateRecipientRegisterInformationRequest RegisterInformation 
        { 
            get 
            {
                return this.registerInformation; 
            } 
            set 
            {
                this.registerInformation = value;
                onPropertyChanged("RegisterInformation");
            }
        }

        /// <summary>
        /// Metadata
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata 
        { 
            get 
            {
                return this.metadata; 
            } 
            set 
            {
                this.metadata = value;
                onPropertyChanged("Metadata");
            }
        }

        private Models.CreateRecipientRegisterInformationRequest GetOrCreateRegisterInformation()
        {
            if (this.registerInformation == null)
            {
                this.registerInformation = new Models.CreateRecipientRegisterInformationRequest();
            }

            return this.registerInformation;
        }

        /// <summary>
        /// Validates recipient update data.
        /// </summary>
        public override void Validate()
        {
            this.registerInformation?.Validate();
        }
    }
} 
